name: Actividad05 - Release NuGet

env:
  DOTNET_VERSION: '8.0'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set version in .csproj
        run: sed -i.bak "s|<PackageVersion>.*</PackageVersion>|<PackageVersion>${VERSION}</PackageVersion>|" Bank/Bank.Domain/Bank.Domain.csproj

      - name: Clean sed backup file
        run: rm Bank/Bank.Domain/Bank.Domain.csproj.bak

      - name: Restore dependencies && Build solution
        run: |
          cd Bank
          dotnet restore
          dotnet build --configuration Release

      - name: Pack NuGet package
        run: |
          dotnet pack Bank/Bank.Domain/Bank.Domain.csproj -c Release --output ./nupkg -p:PackageVersion=${VERSION}

      - name: NuGet sources
        run: dotnet nuget list source

      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push "./nupkg/*.nupkg" --skip-duplicate --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./nupkg/*.nupkg